title: "Duong PH | DSO Profile"
description: "Personal portfolio and blog for Duong PH."
url: "https://duonghaipham.github.io"
baseurl: "/dso-profile"

author:
  name: "Duong Hai Pham"
  github: "duonghaipham"

theme: jekyll-theme-cayman

markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag


exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
